demo:
  number-of-participants: 3
exogenous-events:
  investor-arrivals:
  - investor_focal_T1_10-24-2020_22-42_Stress4.csv
  external-feed:
  - external_feed_T1_10-24-2020_22-42_Stress4.csv
group:
  number-of-groups: 1
  players-per-group: 3
market:
  auction-format: CDA
  matching-engine-host: 127.0.0.1
parameters:
  default-role: out
  include-manual-role: true
  include-signed-volume-widgets: false
  initial-endowment: 100
  k-reference-price: 0.7
  k-signed-volume: 0.5
  session-duration: 20
  tax-rate: 0.1
  technology-unit-cost: 0.01
session:
  currency: EUR
  display-name: TESTING HFT - ELO - CDA - 15 Trade Sessions of 240 seconds - 3 traders - Frequent
    Order Flow
  environment: elo
  exchange-rate: 1.5
  num-rounds: 1
  participation-fee: 4
  session-name: ELO_Development_Session_15_rounds_3traders_240_sec_sv_on
